export var ENTITIES_ACTIONS = {
  SAVE: "ENTITIES.SAVE"
}

export var USER_ACTIONS = {
  FETCH_ONLINE: "USER.FETCH_ONLINE",
  FETCH_FRIENDS: "USER.FETCH_ONLINE",
  FETCH_ME: "USER.FETCH_ONLINE",
  FETCH_PROFILE: "USER.FETCH_ONLINE",
}

