export var ENTITIES_ACTIONS = {
  SAVE: "ENTITIES.SAVE"
}

export var USER_ACTIONS = {
  FETCH_ONLINE: "USER.FETCH_ONLINE",
  FETCH_FRIENDS: "USER.FETCH_ONLINE",
  FETCH_ME: "USER.FETCH_ONLINE",
  FETCH_PROFILE: "USER.FETCH_ONLINE",
}

export var STORY_ACTIONS = {
  FETCH: "STORY.FETCH",
  FETCH_ALL: "STORY.FETCH_ALL",
  CREATE: "STORY.CREATE",
  UPDATE: "STORY.UPDATE"
}
