export var ENTITIES_ACTIONS = {
  SAVE: "ENTITIES.SAVE",
  REMOVE: "ENTITIES.REMOVE"
}

export var USER_ACTIONS = {
  FETCH_ME: "USER.FETCH_ONLINE",
  FETCH_PROFILE: "USER.FETCH_ONLINE",
}

export var STORY_ACTIONS = {
  FETCH_REQUEST: "STORY.FETCH_REQUEST",
  FETCH_SUCCESS: "STORY.FETCH_SUCCESS",
  FETCH_FAILURE: "STORY.FETCH_FAILURE",

  FETCH_LIST_REQUEST: "STORY.FETCH_LIST_REQUEST",
  FETCH_LIST_SUCCESS: "STORY.FETCH_LIST_SUCCESS",
  FETCH_LIST_FAILURE: "STORY.FETCH_LIST_FAILURE",
  
  UPDATE_REQUEST: "STORY.UPDATE_REQUEST",
  UPDATE_SUCCESS: "STORY.UPDATE_SUCCESS",
  UPDATE_FAILURE: "STORY.UPDATE_FAILURE",
  
  REPLACE_REQUEST: "STORY.REPLACE_REQUEST",
  REPLACE_SUCCESS: "STORY.REPLACE_SUCCESS",
  REPLACE_FAILURE: "STORY.REPLACE_FAILURE",
  
  CREATE_REQUEST: "STORY.CREATE_REQUEST",
  CREATE_SUCCESS: "STORY.CREATE_SUCCESS",
  CREATE_FAILURE: "STORY.CREATE_FAILURE",
  
  DELETE_REQUEST: "STORY.DELETE_REQUEST",
  DELETE_SUCCESS: "STORY.DELETE_SUCCESS",
  DELETE_FAILURE: "STORY.DELETE_FAILURE",
}